import { COUNTRIES } from "@/enums/countries";

export const defaultClientEmail = "info@moto-nautika.com";

export const clientEmails = {
  [COUNTRIES.ALBANIA]: "info@moto-nautika.com",
  [COUNTRIES.AUSTRALIA]: "info@grandboats.com.au",
  [COUNTRIES.AUSTRIA]: "post@ms-marine.de",
  [COUNTRIES.BELGIUM]: "info@grandboats.nl",
  [COUNTRIES.BOSNIA_AND_HERZEGOVINA]: "info@moto-nautika.com",
  [COUNTRIES.BULGARIA]: "info@grandboats.gr",
  [COUNTRIES.CANADA]: "mail@gmimarine.com",
  [COUNTRIES.CROATIA]: "info@moto-nautika.com",
  [COUNTRIES.CYPRUS]: "grandboatscyprus@gmail.com",
  [COUNTRIES.CZECH_REPUBLIC]: "yacht@avaryacht.cz",
  [COUNTRIES.ESTONIA]: "sales@grandboatsnordic.com",
  [COUNTRIES.DENMARK]: "info@saildirect.dk",
  [COUNTRIES.FINLAND]: "sales@grandboatsnordic.com",
  [COUNTRIES.FRANCE]: "contact@tonimarine.fr",
  [COUNTRIES.GERMANY]: "post@ms-marine.de",
  [COUNTRIES.GREECE]: "info@grandboats.gr",
  [COUNTRIES.HUNGARY]: "hello@ribstore.net",
  [COUNTRIES.IRELAND]: "info@crawfordsmarina.com",
  [COUNTRIES.ITALY]: "info@emeraldboats.com",
  [COUNTRIES.KOSOVO]: "info@moto-nautika.com",
  [COUNTRIES.LATVIA]: "sales@grandboatsnordic.com",
  [COUNTRIES.LITHUANIA]: "sales@grandboatsnordic.com",
  [COUNTRIES.LUXEMBOURG]: "info@grandboats.nl",
  [COUNTRIES.MALTA]: "info@petecraft.com",
  [COUNTRIES.MARTINIQUE]: "yamahafwi@orange.fr",
  [COUNTRIES.MONTENEGRO]: "info@moto-nautika.com",
  [COUNTRIES.NETHERLANDS]: "Info@grandboats.nl",
  [COUNTRIES.NEW_ZEALAND]: "Sales@grandinflatables.co.nz",
  [COUNTRIES.NORTH_CYPRUS]: "info@fisher-town.com",
  [COUNTRIES.NORTH_MACEDONIA]: "info@moto-nautika.com",
  [COUNTRIES.NORWAY]: "post@govi.no",
  [COUNTRIES.POLAND]: "info@grandboats.pl",
  [COUNTRIES.PORTUGAL_FARO]: "info@nauticolour.pt",
  [COUNTRIES.PORTUGAL_LAGOS]: "sean@algarveboatgroup.com",
  [COUNTRIES.PUERTO_RICO]: "sales@grandboats.us",
  [COUNTRIES.QATAR]: "ravi@themarineplace.com",
  [COUNTRIES.ROMANIA]: "info@grandboats.gr",
  [COUNTRIES.SERBIA]: "info@moto-nautika.com",
  [COUNTRIES.SLOVAKIA]: "yacht@avaryacht.cz",
  [COUNTRIES.SLOVENIA]: "info@moto-nautika.com",
  [COUNTRIES.SPAIN]: "mail@grandmarine.es",
  [COUNTRIES.SPAIN_BALEARIC]: "comercial@multimaralcudia.es",
  [COUNTRIES.SPAIN_CANARY]: "tacoronte@isaboats.com",
  [COUNTRIES.SWEDEN]: "rodins@rodinsmarin.se",
  [COUNTRIES.SWITZERLAND]: "post@ms-marine.de",
  [COUNTRIES.TURKEY]: "info@mercurysport.com",
  [COUNTRIES.UKRAINE]: "info@grand.ua",
  [COUNTRIES.UAE]: "info@empire-marine.com",
  [COUNTRIES.UNITED_KINGDOM]: "info@willsmarine.co.uk",
  [COUNTRIES.USA]: "sales@grandboats.us",
};
